# variable "profile" {
#   default = "klopac"
# }

variable "environment" {
  default = "test"
}

variable "region" {
  default = "eu-west-1"
}

variable "role" {
  default = "arn:aws:iam::417732881703:role/eks-admin"
}

# variable "elb-name" {
#   default = "Devops-AwsCluster-Elb"
# }

variable "ami_id" {
  default = "ami-08ca3fed11864d6bb"
}

variable "security_group_name" {
  default = "klopac"
}

variable "security_group_id" {
  default = "sg-09a98cb92b42e82a1"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "vpc_id" {
  default = "vpc-024f3e66"
}

variable "worker_instance_type" {
  default = "t2.micro"
}

variable "master_instance_type" {
  default = "t2.micro"
}

variable "subnet_id1" {
  default = "subnet-ec04449a"
}

variable "subnet_id2" {
  default = "subnet-f9b3fb9d"
}

variable "iam_policy" {
  default = "eks-all"
}

variable "cidr_blocks" {
  default = ["172.31.0.0/16"]
}

variable "worker_min_size" {
  default = 2
}

variable "worker_max_size" {
  default = 2
}

variable "worker_desired_size" {
  default = 2
}

variable "master_min_size" {
  default = 2
}

variable "master_max_size" {
  default = 2
}

variable "master_desired_size" {
  default = 2
}